# argocd-apps/root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Points to this repository's argocd-apps folder
  source:
    repoURL: https://github.com/Himansri21/GCP-cluster-terraform
    targetRevision: main
    path: argocd-apps
    directory:
      recurse: false  # Don't recurse into subdirectories
      include: '{argocd-app.yaml,website-app.yaml}'  # Only these files
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true